name: FazeDesigns
favicon: null
layout_spectrum: 0.45676506753079593
typography_spectrum: 0.5232613757252693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5549065077211708
  lightness: 0.8541145178023726
  saturation: 0.3198686314281076
  rhythmicContrast: 0.9437438056338578
purpose: []
