name: FazeDesigns
favicon: null
layout_spectrum: 0.0735
typography_spectrum: 0.61954
title: FazeDesigns
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dad9d4'
    - '#626167'
    - '#0d0d17'
    - '#413f4c'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
