name: FazeDesigns
favicon: null
layout_spectrum: 0.45676506753079593
typography_spectrum: 0.5232613757252693
title: FazeDesigns
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dad9d4'
    - '#626167'
    - '#0d0d17'
    - '#413f4c'
  brandStrength: 0.75
  lightness: 0.8541145178023726
  saturation: 0.3198686314281076
  rhythmicContrast: 0.9437438056338578
purpose: []
