name: FazeDesigns
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61954
title: FazeDesigns
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353a40'
    - '#ea594c'
    - '#fffdd4'
    - '#418076'
    - '#4fe6c3'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
